[package]
name = "risc-v-gen"
version = "0.1.0"
edition = "2025"
description = "RISC-V code generation utilities"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/uplc-risc"

[dependencies]
# Core dependencies
log = { workspace = true }
riscv-decode = "0.2.1"
thiserror = { workspace = true }

# BitVMX-CPU dependencies
bitcoin-script-riscv = { git = "https://github.com/FairgateLabs/BitVMX-CPU", branch = "main", package = "bitcoin-script-riscv" }
sha2 = "0.10.8"
hex = "0.4.3"

[features]
default = [] 
